version: 2
updates:
  - package-ecosystem: poetry
    directory: "/"
    schedule:
      interval: monthly
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
