[tool.poetry]
name = "hetznerbot"
version = "1.0.0"
description = "A bot for getting the nicest offers from hetzner"
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/hetznerbot"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "6.10"
python-telegram-bot = "^12.0.0"
SQLAlchemy = "^1.2"
sqlalchemy-utils = "^0.34"
psycopg2-binary = "^2.8"
toml = "^0.10"
requests = "^2.18"
dateparser = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
