"""remove: Legacy fields

Revision ID: 2f13652a0b5c
Revises: 2fdb5eeeecf1
Create Date: 2022-12-26 18:11:35.731133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f13652a0b5c'
down_revision = '2fdb5eeeecf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'next_reduction')
    op.drop_column('offer', 'cpu_rating')
    op.drop_column('subscriber', 'cpu_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('cpu_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('cpu_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('next_reduction', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
