"""remove: Add ipv4 special

Revision ID: 2189c235fcaf
Revises: 2f13652a0b5c
Create Date: 2022-12-30 10:42:59.120608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2189c235fcaf'
down_revision = '2f13652a0b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('ipv4', sa.Boolean(), server_default='FALSE', nullable=False))
    op.alter_column('offer', 'deactivated',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.alter_column('offer', 'ecc',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.alter_column('offer', 'inic',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.alter_column('offer', 'hwr',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.add_column('subscriber', sa.Column('ipv4', sa.Boolean(), server_default='FALSE', nullable=False))
    op.alter_column('subscriber', 'ecc',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.alter_column('subscriber', 'inic',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    op.alter_column('subscriber', 'hwr',
               existing_type=sa.BOOLEAN(),
               server_default='FALSE',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriber', 'hwr',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriber', 'inic',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriber', 'ecc',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('subscriber', 'ipv4')
    op.alter_column('offer', 'hwr',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('offer', 'inic',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('offer', 'ecc',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('offer', 'deactivated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('offer', 'ipv4')
    # ### end Alembic commands ###
