"""add: Move new flag to subscrpition instead of offer.

Revision ID: ca64e61eae56
Revises: 37ebb30c61ba
Create Date: 2023-01-07 15:54:55.192167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca64e61eae56'
down_revision = '37ebb30c61ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'new')
    op.add_column('offer_subscriber', sa.Column('new', sa.Boolean(), server_default='FALSE', nullable=False))
    op.alter_column('offer_subscriber', 'notified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer_subscriber', 'notified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('offer_subscriber', 'new')
    op.add_column('offer', sa.Column('new', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
