"""new table for disk type

Revision ID: 0572b3aadca3
Revises: ca64e61eae56
Create Date: 2023-04-12 20:21:44.135576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0572b3aadca3'
down_revision = 'ca64e61eae56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_disk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('hdd', 'sata', 'nvme', name='disktype'), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.SmallInteger(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_disk_offer_id'), 'offer_disk', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_disk_offer_id'), table_name='offer_disk')
    op.drop_table('offer_disk')
    # ### end Alembic commands ###
