"""add: Add flag to distinguish new and reduced offers

Revision ID: 37ebb30c61ba
Revises: 2189c235fcaf
Create Date: 2023-01-01 15:28:53.210180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ebb30c61ba'
down_revision = '2189c235fcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('new', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'new')
    # ### end Alembic commands ###
