"""remove unused columns

Revision ID: 8e555602a405
Revises: 0572b3aadca3
Create Date: 2023-04-12 23:29:40.300631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e555602a405'
down_revision = '0572b3aadca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'hdd_count')
    op.drop_column('offer', 'hdd_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('hdd_size', sa.FLOAT(), nullable=False))
    op.add_column('offer', sa.Column('hdd_count', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
