name: Lint

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: hetznerbot

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
      fail-fast: false

    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      # This has been done according to https://docs.makedeb.org/prebuilt-mpr/getting-started/
      # This is needed for packages: just
      - name: Add makedb debian user repository
        run: |
          curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
          echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
          sudo apt update

      - name: Install just
        run: sudo apt install just

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Only run taplo on linux to save some time.
      - name: Install taplo-cli
        run: cargo install taplo-cli || exit 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: just setup

      - name: Lint
        run: just lint
